on:
  push:

jobs:
  get-version:
    uses: shiipou/github-actions/.github/workflows/get-version.yml@main
    with:
      release-branches: '^(main)$'
    

  build:
   name: Spring build
   runs-on: ubuntu-latest
   needs: 
     - get-version
   steps:
     - name: Print version
       run: |
         echo "${{ needs.get-version.outputs.version }}"
         echo "${{ needs.get-version.outputs.changelogs }}"
         echo "${{ needs.get-version.outputs.is-prerelease }}"
         echo "${{ needs.get-version.outputs.will-release }}"
     - name: Setup java
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: 17
     - name: Setup gradle
       uses: gradle/actions/setup-gradle@v4
     - name: Checkout clone source code
       uses: actions/checkout@v4
     - name: Build with Gradle
       run: ./gradlew bootjar
     - run: ls -lia build/libs
